"use client";
import { useMemo, useState } from "react";

const products=[
 {id:1,name:"Trà đào cam sả",cat:"Trà trái cây",price:49000,icon:"🍑",tone:"peach",image:"/olala-website/images/tea-duo.png",side:"left",tag:"Bán chạy",desc:"Đào giòn, cam vàng và sả thơm dịu"},
 {id:2,name:"Cà phê kem muối",cat:"Cà phê",price:45000,icon:"☕",tone:"coffee",image:"/olala-website/images/coffee-duo.png",side:"left",tag:"Yêu thích",desc:"Cà phê đậm, kem muối mềm mịn"},
 {id:3,name:"Nước ép xanh",cat:"Healthy",price:59000,icon:"🥬",tone:"green",image:"/olala-website/images/juice-duo.png",side:"left",tag:"Ít calo",desc:"Táo, cải kale, cần tây và chanh"},
 {id:4,name:"Trà ô long dâu",cat:"Trà trái cây",price:55000,icon:"🍓",tone:"berry",image:"/olala-website/images/tea-duo.png",side:"right",tag:"Mới",desc:"Dâu tươi hòa cùng ô long thanh nhẹ"},
 {id:5,name:"Cold brew cam",cat:"Cà phê",price:52000,icon:"🍊",tone:"orange",image:"/olala-website/images/coffee-duo.png",side:"right",tag:"Tỉnh táo",desc:"Cold brew ủ lạnh cùng cam vàng"},
 {id:6,name:"Nước ép nhiệt đới",cat:"Healthy",price:62000,icon:"🥭",tone:"mango",image:"/olala-website/images/juice-duo.png",side:"right",tag:"Vitamin C",desc:"Xoài, dứa, chanh leo giàu vitamin"}
];
const money=(n:number)=>new Intl.NumberFormat("vi-VN").format(n)+"đ";
const toppingPrices:Record<string,number>={"Trân châu trắng":8000,"Thạch đào":8000,"Hạt chia":6000,"Kem muối":10000};

export default function Home(){
 const [cat,setCat]=useState("Tất cả"),[cart,setCart]=useState<Record<number,number>>({}),[open,setOpen]=useState(false),[checkout,setCheckout]=useState(false),[success,setSuccess]=useState(false),[pay,setPay]=useState("cod");
 const [selected,setSelected]=useState<number|null>(null),[size,setSize]=useState("M"),[sugar,setSugar]=useState("50%"),[ice,setIce]=useState("Vừa"),[added,setAdded]=useState<number|null>(null),[fly,setFly]=useState<number|null>(null),[toast,setToast]=useState("");
 const [toppings,setToppings]=useState<string[]>([]),[prefs,setPrefs]=useState<Record<number,{size:string,sugar:string,ice:string,toppings:string[]}>>({});
 const shown=cat==="Tất cả"?products:products.filter(p=>p.cat===cat), count=Object.values(cart).reduce((a,b)=>a+b,0);
 const itemPrice=(id:number,base:number)=>base+(prefs[id]?.size==="L"?8000:0)+(prefs[id]?.toppings||[]).reduce((sum,t)=>sum+toppingPrices[t],0);
 const subtotal=useMemo(()=>products.reduce((s,p)=>s+itemPrice(p.id,p.price)*(cart[p.id]||0),0),[cart,prefs]),shipping=subtotal&&subtotal<150000?15000:0;
 const change=(id:number,d:number)=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)+d)}));
 const add=(id:number)=>{change(id,1);setAdded(id);setFly(id);setToast(`Đã thêm ${products.find(p=>p.id===id)?.name}`);window.setTimeout(()=>setAdded(null),550);window.setTimeout(()=>setFly(null),700);window.setTimeout(()=>setToast(""),2400)};
 const showDetail=(id:number)=>{const old=prefs[id];setSelected(id);setSize(old?.size||"M");setSugar(old?.sugar||"50%");setIce(old?.ice||"Vừa");setToppings(old?.toppings||[])};
 const saveChoice=()=>{if(selected===null)return;setPrefs(p=>({...p,[selected]:{size,sugar,ice,toppings}}));add(selected);setSelected(null)};
 const addCombo=(ids:number[])=>{ids.forEach((id,i)=>window.setTimeout(()=>add(id),i*120))};
 const toggleTopping=(name:string)=>setToppings(t=>t.includes(name)?t.filter(x=>x!==name):[...t,name]);
 const selectedProduct=products.find(p=>p.id===selected);
 const freeLeft=Math.max(0,150000-subtotal),progress=Math.min(100,(subtotal/150000)*100);
 return <main>
  <header className="nav shell"><a className="brand" href="#top"><span>o</span>lala</a><nav><a href="#menu">Thực đơn</a><a href="#story">Về OLALA</a><a href="#contact">Liên hệ</a></nav><button className="cartBtn" onClick={()=>setOpen(true)}>Giỏ hàng <b>{count}</b></button></header>
  <section className="hero shell" id="top"><div><div className="eyebrow">TƯƠI MỖI NGÀY · GIAO NHANH 30 PHÚT</div><h1>Một ngụm tươi,<br/><em>cả ngày vui.</em></h1><p>Trà thơm, cà phê đậm vị và nước ép nguyên chất — được pha mới ngay khi bạn đặt.</p><div className="heroActions"><a href="#menu" className="primary">Khám phá thực đơn →</a><span>★ 4.9 <small>từ hơn 1.200 khách hàng</small></span></div></div><div className="heroArt realHero"><div className="sun"/><img src="/olala-website/images/tea-duo.png" alt="Trà trái cây tươi OLALA"/><div className="heroBubble b1">100% trái cây thật</div><div className="heroBubble b2">Pha mới mỗi ngày</div><i className="fruit f1">🍊</i><i className="fruit f2">🍃</i></div></section>
  <div className="benefits"><div>🌿 <b>Nguyên liệu tươi</b><span>Chọn lọc mỗi ngày</span></div><div>🧊 <b>Pha mới khi đặt</b><span>Không dùng đồ pha sẵn</span></div><div>⚡ <b>Giao nhanh 30 phút</b><span>Trong bán kính 5km</span></div></div>
  <section className="menu shell" id="menu"><div className="sectionHead"><div><span>BEST SELLER</span><h2>Hôm nay uống gì?</h2></div><p>Mỗi món là một công thức cân bằng giữa hương vị và năng lượng lành mạnh.</p></div><div className="filters">{["Tất cả","Trà trái cây","Cà phê","Healthy"].map(x=><button className={cat===x?"active":""} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className="grid">{shown.map((p,index)=><article style={{animationDelay:`${index*70}ms`}} className={`product reveal ${cart[p.id]?"inCart":""} ${added===p.id?"justAdded":""}`} key={p.id}><button className={`productArt photo ${p.tone}`} onClick={()=>showDetail(p.id)} aria-label={`Xem tùy chọn ${p.name}`}><img className={`duo ${p.side}`} src={p.image} alt={p.name}/><i>OLALA</i><div className="productTag">{p.tag}</div>{cart[p.id]>0&&<div className="addedBadge">✓ Đã thêm</div>}</button><div className="productInfo"><small>{p.cat}</small><button className="nameBtn" onClick={()=>showDetail(p.id)}><h3>{p.name}</h3></button><p>{p.desc}</p><div><b>{money(p.price)} <small>từ</small></b>{cart[p.id]?<div className="cardQty"><button onClick={()=>change(p.id,-1)} aria-label={`Giảm ${p.name}`}>−</button><strong>{cart[p.id]}</strong><button onClick={()=>add(p.id)} aria-label={`Thêm ${p.name}`}>+</button></div>:<button className="addBtn" onClick={()=>add(p.id)} aria-label={`Thêm ${p.name} vào giỏ`}>+</button>}</div><button className="customize" onClick={()=>showDetail(p.id)}>Tùy chỉnh size · đường · đá</button></div></article>)}</div></section>
  <section className="combos shell"><div className="sectionHead"><div><span>GỢI Ý KẾT HỢP</span><h2>Uống cùng vui hơn</h2></div><p>Những cặp đồ uống được khách OLALA chọn nhiều nhất.</p></div><div className="comboGrid"><article><div className="comboPics"><span>☕</span><b>+</b><span>🥬</span></div><div><small>COMBO BUỔI SÁNG</small><h3>Cà phê kem muối + Nước ép xanh</h3><p><strong>104.000đ</strong></p><button onClick={()=>addCombo([2,3])}>Thêm 2 món →</button></div></article><article><div className="comboPics"><span>🍑</span><b>+</b><span>🍓</span></div><div><small>COMBO 2 NGƯỜI</small><h3>Trà đào cam sả + Trà ô long dâu</h3><p><strong>104.000đ</strong></p><button onClick={()=>addCombo([1,4])}>Thêm 2 món →</button></div></article></div></section>
  <section className="story" id="story"><div className="shell storyInner"><div className="storyArt">OLALA<span>fresh & happy</span></div><div><span className="eyebrow">CHUYỆN CỦA OLALA</span><h2>Uống ngon,<br/>sống lành hơn.</h2><p>Chúng mình tin rằng một ly nước ngon không cần quá nhiều đường hay hương liệu. OLALA ưu tiên trái cây tươi, trà nguyên lá và cà phê rang mới.</p><div className="stats"><b>100%<small>trái cây thật</small></b><b>0<small>chất bảo quản</small></b><b>30′<small>giao tận tay</small></b></div></div></div></section>
  <section className="reviews shell"><div className="reviewTitle"><span className="eyebrow">KHÁCH HÀNG NÓI GÌ?</span><h2>Những ngụm vui<br/>được chia sẻ.</h2></div><div className="reviewTrack"><article><div>★★★★★</div><p>“Trà thơm, không quá ngọt. Giao tới nơi đá vẫn chưa tan nhiều.”</p><b>Minh Anh</b><small>Đã đặt 12 lần</small></article><article><div>★★★★★</div><p>“Cà phê kem muối đậm vừa đủ, phần kem rất mịn và không bị ngấy.”</p><b>Hoàng Nam</b><small>Khách hàng thân thiết</small></article><article><div>★★★★★</div><p>“Nước ép xanh dễ uống hơn mình nghĩ, vị tươi và không bị quá nồng cần tây.”</p><b>Thu Hà</b><small>Đã đặt 8 lần</small></article></div></section>
  <footer id="contact"><div className="shell footer"><div className="brand"><span>o</span>lala</div><p>Đồ uống tươi cho ngày vui hơn.<br/>Hotline: 090 123 4567</p><div>Instagram　Facebook　TikTok</div></div></footer>
  {count>0&&!open&&<div className="floatingWrap"><div className="freeProgress"><span style={{width:`${progress}%`}}/>{freeLeft?<small>Mua thêm {money(freeLeft)} để miễn phí giao hàng</small>:<small>🎉 Bạn được miễn phí giao hàng</small>}</div><button className="floatingCart" onClick={()=>setOpen(true)} aria-label={`Mở giỏ hàng có ${count} sản phẩm`}><span className="floatingCount">{count}</span><span><b>Xem giỏ hàng</b><small>{count} món đã chọn</small></span><strong>{money(subtotal+shipping)}　→</strong></button></div>}
  {fly&&<div className="flyToCart">{products.find(p=>p.id===fly)?.icon}</div>}
  {toast&&<div className="toast"><b>✓</b><span>{toast}<small>Đã cập nhật giỏ hàng</small></span><button onClick={()=>setToast("")}>×</button></div>}
  {open&&<div className="overlay" onMouseDown={()=>setOpen(false)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}>×</button>
   {!checkout&&!success&&<><h2>Giỏ hàng của bạn</h2>{count===0?<div className="empty">🧃<p>Giỏ hàng đang trống</p><button onClick={()=>setOpen(false)}>Chọn đồ uống</button></div>:<><div className="drawerProgress"><div><span style={{width:`${progress}%`}}/></div><p>{freeLeft?<>Thêm <b>{money(freeLeft)}</b> để được miễn phí giao hàng</>:<>🎉 Đơn hàng được miễn phí giao hàng</>}</p></div><div>{products.filter(p=>cart[p.id]).map(p=><div className="cartItem" key={p.id}><span>{p.icon}</span><div><b>{p.name}</b><small>{prefs[p.id]?`${prefs[p.id].size} · ${prefs[p.id].sugar} đường · đá ${prefs[p.id].ice}`:"Size M · 50% đường · đá vừa"}</small>{prefs[p.id]?.toppings.length>0&&<small>+ {prefs[p.id].toppings.join(", ")}</small>}<small>{money(itemPrice(p.id,p.price))}</small></div><div className="qty"><button onClick={()=>change(p.id,-1)}>−</button>{cart[p.id]}<button onClick={()=>add(p.id)}>+</button></div></div>)}</div><div className="summary"><p>Tạm tính <b>{money(subtotal)}</b></p><p>Phí giao hàng <b>{shipping?money(shipping):"Miễn phí"}</b></p><p className="total">Tổng cộng <b>{money(subtotal+shipping)}</b></p></div><button className="checkout" onClick={()=>setCheckout(true)}>Tiến hành đặt hàng</button></>}</>}
   {checkout&&!success&&<form onSubmit={e=>{e.preventDefault();setSuccess(true)}}><button type="button" className="back" onClick={()=>setCheckout(false)}>← Quay lại giỏ hàng</button><h2>Thông tin giao hàng</h2><label>Họ và tên<input required placeholder="Nguyễn Văn An"/></label><label>Số điện thoại<input required type="tel" placeholder="09xx xxx xxx"/></label><label>Địa chỉ giao hàng<textarea required placeholder="Số nhà, đường, phường/xã, quận/huyện"/></label><label>Ghi chú<textarea placeholder="Ít đá, giao tại lễ tân..."/></label><h3>Thanh toán</h3><label className={`payment ${pay==="cod"?"selected":""}`}><input type="radio" name="pay" checked={pay==="cod"} onChange={()=>setPay("cod")}/>💵 Thanh toán khi nhận hàng</label><label className={`payment ${pay==="online"?"selected":""}`}><input type="radio" name="pay" checked={pay==="online"} onChange={()=>setPay("online")}/>💳 Thanh toán trực tuyến</label>{pay==="online"&&<div className="note">Cổng thanh toán sẽ mở sau khi xác nhận đơn.</div>}<button className="checkout" type="submit">Đặt hàng · {money(subtotal+shipping)}</button></form>}
   {success&&<div className="success"><div>✓</div><h2>Đặt hàng thành công!</h2><p>OLALA đã nhận đơn và sẽ liên hệ xác nhận trong ít phút.</p><button onClick={()=>{setCart({});setSuccess(false);setCheckout(false);setOpen(false)}}>Tiếp tục mua hàng</button></div>}
  </aside></div>}
  {selectedProduct&&<div className="overlay detailOverlay" onMouseDown={()=>setSelected(null)}><section className="detailModal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className={`detailPhoto ${selectedProduct.tone}`}><img className={`duo ${selectedProduct.side}`} src={selectedProduct.image} alt={selectedProduct.name}/><div className="liveChoice">Size {size}<br/>{sugar} đường · đá {ice.toLowerCase()}</div></div><div className="detailBody"><span className="eyebrow">TÙY CHỈNH MÓN</span><h2>{selectedProduct.name}</h2><p>{selectedProduct.desc}</p><Option title="Chọn size" values={["M","L +8.000đ"]} current={size==="L"?"L +8.000đ":"M"} onPick={v=>setSize(v.startsWith("L")?"L":"M")}/><Option title="Lượng đường" values={["0%","30%","50%","100%"]} current={sugar} onPick={setSugar}/><Option title="Lượng đá" values={["Ít","Vừa","Nhiều"]} current={ice} onPick={setIce}/><div className="optionGroup"><b>Thêm topping</b><div>{Object.entries(toppingPrices).map(([name,price])=><button key={name} className={toppings.includes(name)?"selected":""} onClick={()=>toggleTopping(name)}>{toppings.includes(name)?"✓ ":""}{name} +{money(price)}</button>)}</div></div><button className="checkout addCustomized" onClick={saveChoice}>Thêm vào giỏ · {money(selectedProduct.price+(size==="L"?8000:0)+toppings.reduce((sum,t)=>sum+toppingPrices[t],0))}</button></div></section></div>}
 </main>
}

function Option({title,values,current,onPick}:{title:string,values:string[],current:string,onPick:(value:string)=>void}){return <div className="optionGroup"><b>{title}</b><div>{values.map(v=><button key={v} className={current===v?"selected":""} onClick={()=>onPick(v)}>{v}</button>)}</div></div>}
