"use client";
import { useMemo, useState } from "react";

const products=[
 {id:1,name:"TrÃ  Ä‘Ã o cam sáº£",cat:"TrÃ  trÃ¡i cÃ¢y",price:49000,icon:"ðŸ‘",tone:"peach",image:"/olala-website/images/tea-duo.png",side:"left",tag:"BÃ¡n cháº¡y",desc:"ÄÃ o giÃ²n, cam vÃ ng vÃ  sáº£ thÆ¡m dá»‹u"},
 {id:2,name:"CÃ  phÃª kem muá»‘i",cat:"CÃ  phÃª",price:45000,icon:"â˜•",tone:"coffee",image:"/olala-website/images/coffee-duo.png",side:"left",tag:"YÃªu thÃ­ch",desc:"CÃ  phÃª Ä‘áº­m, kem muá»‘i má»m má»‹n"},
 {id:3,name:"NÆ°á»›c Ã©p xanh",cat:"Healthy",price:59000,icon:"ðŸ¥¬",tone:"green",image:"/olala-website/images/juice-duo.png",side:"left",tag:"Ãt calo",desc:"TÃ¡o, cáº£i kale, cáº§n tÃ¢y vÃ  chanh"},
 {id:4,name:"TrÃ  Ã´ long dÃ¢u",cat:"TrÃ  trÃ¡i cÃ¢y",price:55000,icon:"ðŸ“",tone:"berry",image:"/olala-website/images/tea-duo.png",side:"right",tag:"Má»›i",desc:"DÃ¢u tÆ°Æ¡i hÃ²a cÃ¹ng Ã´ long thanh nháº¹"},
 {id:5,name:"Cold brew cam",cat:"CÃ  phÃª",price:52000,icon:"ðŸŠ",tone:"orange",image:"/olala-website/images/coffee-duo.png",side:"right",tag:"Tá»‰nh tÃ¡o",desc:"Cold brew á»§ láº¡nh cÃ¹ng cam vÃ ng"},
 {id:6,name:"NÆ°á»›c Ã©p nhiá»‡t Ä‘á»›i",cat:"Healthy",price:62000,icon:"ðŸ¥­",tone:"mango",image:"/olala-website/images/juice-duo.png",side:"right",tag:"Vitamin C",desc:"XoÃ i, dá»©a, chanh leo giÃ u vitamin"}
];
const money=(n:number)=>new Intl.NumberFormat("vi-VN").format(n)+"Ä‘";
const toppingPrices:Record<string,number>={"TrÃ¢n chÃ¢u tráº¯ng":8000,"Tháº¡ch Ä‘Ã o":8000,"Háº¡t chia":6000,"Kem muá»‘i":10000};

export default function Home(){
 const [cat,setCat]=useState("Táº¥t cáº£"),[cart,setCart]=useState<Record<number,number>>({}),[open,setOpen]=useState(false),[checkout,setCheckout]=useState(false),[success,setSuccess]=useState(false),[pay,setPay]=useState("cod");
 const [selected,setSelected]=useState<number|null>(null),[size,setSize]=useState("M"),[sugar,setSugar]=useState("50%"),[ice,setIce]=useState("Vá»«a"),[added,setAdded]=useState<number|null>(null),[fly,setFly]=useState<number|null>(null),[toast,setToast]=useState("");
 const [toppings,setToppings]=useState<string[]>([]),[prefs,setPrefs]=useState<Record<number,{size:string,sugar:string,ice:string,toppings:string[]}>>({});
 const shown=cat==="Táº¥t cáº£"?products:products.filter(p=>p.cat===cat), count=Object.values(cart).reduce((a,b)=>a+b,0);
 const itemPrice=(id:number,base:number)=>base+(prefs[id]?.size==="L"?8000:0)+(prefs[id]?.toppings||[]).reduce((sum,t)=>sum+toppingPrices[t],0);
 const subtotal=useMemo(()=>products.reduce((s,p)=>s+itemPrice(p.id,p.price)*(cart[p.id]||0),0),[cart,prefs]),shipping=subtotal&&subtotal<150000?15000:0;
 const change=(id:number,d:number)=>setCart(c=>({...c,[id]:Math.max(0,(c[id]||0)+d)}));
 const add=(id:number)=>{change(id,1);setAdded(id);setFly(id);setToast(`ÄÃ£ thÃªm ${products.find(p=>p.id===id)?.name}`);window.setTimeout(()=>setAdded(null),550);window.setTimeout(()=>setFly(null),700);window.setTimeout(()=>setToast(""),2400)};
 const showDetail=(id:number)=>{const old=prefs[id];setSelected(id);setSize(old?.size||"M");setSugar(old?.sugar||"50%");setIce(old?.ice||"Vá»«a");setToppings(old?.toppings||[])};
 const saveChoice=()=>{if(selected===null)return;setPrefs(p=>({...p,[selected]:{size,sugar,ice,toppings}}));add(selected);setSelected(null)};
 const addCombo=(ids:number[])=>{ids.forEach((id,i)=>window.setTimeout(()=>add(id),i*120))};
 const toggleTopping=(name:string)=>setToppings(t=>t.includes(name)?t.filter(x=>x!==name):[...t,name]);
 const selectedProduct=products.find(p=>p.id===selected);
 const freeLeft=Math.max(0,150000-subtotal),progress=Math.min(100,(subtotal/150000)*100);
 return <main>
  <header className="nav shell"><a className="brand" href="#top"><span>o</span>lala</a><nav><a href="#menu">Thá»±c Ä‘Æ¡n</a><a href="#story">Vá» OLALA</a><a href="#contact">LiÃªn há»‡</a></nav><button className="cartBtn" onClick={()=>setOpen(true)}>Giá» hÃ ng <b>{count}</b></button></header>
  <section className="hero shell" id="top"><div><div className="eyebrow">TÆ¯Æ I Má»–I NGÃ€Y Â· GIAO NHANH 30 PHÃšT</div><h1>Má»™t ngá»¥m tÆ°Æ¡i,<br/><em>cáº£ ngÃ y vui.</em></h1><p>TrÃ  thÆ¡m, cÃ  phÃª Ä‘áº­m vá»‹ vÃ  nÆ°á»›c Ã©p nguyÃªn cháº¥t â€” Ä‘Æ°á»£c pha má»›i ngay khi báº¡n Ä‘áº·t.</p><div className="heroActions"><a href="#menu" className="primary">KhÃ¡m phÃ¡ thá»±c Ä‘Æ¡n â†’</a><span>â˜… 4.9 <small>tá»« hÆ¡n 1.200 khÃ¡ch hÃ ng</small></span></div></div><div className="heroArt realHero"><div className="sun"/><img src="/olala-website/images/tea-duo.png" alt="TrÃ  trÃ¡i cÃ¢y tÆ°Æ¡i OLALA"/><div className="heroBubble b1">100% trÃ¡i cÃ¢y tháº­t</div><div className="heroBubble b2">Pha má»›i má»—i ngÃ y</div><i className="fruit f1">ðŸŠ</i><i className="fruit f2">ðŸƒ</i></div></section>
  <div className="benefits"><div>ðŸŒ¿ <b>NguyÃªn liá»‡u tÆ°Æ¡i</b><span>Chá»n lá»c má»—i ngÃ y</span></div><div>ðŸ§Š <b>Pha má»›i khi Ä‘áº·t</b><span>KhÃ´ng dÃ¹ng Ä‘á»“ pha sáºµn</span></div><div>âš¡ <b>Giao nhanh 30 phÃºt</b><span>Trong bÃ¡n kÃ­nh 5km</span></div></div>
  <section className="menu shell" id="menu"><div className="sectionHead"><div><span>BEST SELLER</span><h2>HÃ´m nay uá»‘ng gÃ¬?</h2></div><p>Má»—i mÃ³n lÃ  má»™t cÃ´ng thá»©c cÃ¢n báº±ng giá»¯a hÆ°Æ¡ng vá»‹ vÃ  nÄƒng lÆ°á»£ng lÃ nh máº¡nh.</p></div><div className="filters">{["Táº¥t cáº£","TrÃ  trÃ¡i cÃ¢y","CÃ  phÃª","Healthy"].map(x=><button className={cat===x?"active":""} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><div className="grid">{shown.map((p,index)=><article style={{animationDelay:`${index*70}ms`}} className={`product reveal ${cart[p.id]?"inCart":""} ${added===p.id?"justAdded":""}`} key={p.id}><button className={`productArt photo ${p.tone}`} onClick={()=>showDetail(p.id)} aria-label={`Xem tÃ¹y chá»n ${p.name}`}><img className={`duo ${p.side}`} src={p.image} alt={p.name}/><i>OLALA</i><div className="productTag">{p.tag}</div>{cart[p.id]>0&&<div className="addedBadge">âœ“ ÄÃ£ thÃªm</div>}</button><div className="productInfo"><small>{p.cat}</small><button className="nameBtn" onClick={()=>showDetail(p.id)}><h3>{p.name}</h3></button><p>{p.desc}</p><div><b>{money(p.price)} <small>tá»«</small></b>{cart[p.id]?<div className="cardQty"><button onClick={()=>change(p.id,-1)} aria-label={`Giáº£m ${p.name}`}>âˆ’</button><strong>{cart[p.id]}</strong><button onClick={()=>add(p.id)} aria-label={`ThÃªm ${p.name}`}>+</button></div>:<button className="addBtn" onClick={()=>add(p.id)} aria-label={`ThÃªm ${p.name} vÃ o giá»`}>+</button>}</div><button className="customize" onClick={()=>showDetail(p.id)}>TÃ¹y chá»‰nh size Â· Ä‘Æ°á»ng Â· Ä‘Ã¡</button></div></article>)}</div></section>
  <section className="combos shell"><div className="sectionHead"><div><span>Gá»¢I Ã Káº¾T Há»¢P</span><h2>Uá»‘ng cÃ¹ng vui hÆ¡n</h2></div><p>Nhá»¯ng cáº·p Ä‘á»“ uá»‘ng Ä‘Æ°á»£c khÃ¡ch OLALA chá»n nhiá»u nháº¥t.</p></div><div className="comboGrid"><article><div className="comboPics"><span>â˜•</span><b>+</b><span>ðŸ¥¬</span></div><div><small>COMBO BUá»”I SÃNG</small><h3>CÃ  phÃª kem muá»‘i + NÆ°á»›c Ã©p xanh</h3><p><strong>104.000Ä‘</strong></p><button onClick={()=>addCombo([2,3])}>ThÃªm 2 mÃ³n â†’</button></div></article><article><div className="comboPics"><span>ðŸ‘</span><b>+</b><span>ðŸ“</span></div><div><small>COMBO 2 NGÆ¯á»œI</small><h3>TrÃ  Ä‘Ã o cam sáº£ + TrÃ  Ã´ long dÃ¢u</h3><p><strong>104.000Ä‘</strong></p><button onClick={()=>addCombo([1,4])}>ThÃªm 2 mÃ³n â†’</button></div></article></div></section>
  <section className="story" id="story"><div className="shell storyInner"><div className="storyArt">OLALA<span>fresh & happy</span></div><div><span className="eyebrow">CHUYá»†N Cá»¦A OLALA</span><h2>Uá»‘ng ngon,<br/>sá»‘ng lÃ nh hÆ¡n.</h2><p>ChÃºng mÃ¬nh tin ráº±ng má»™t ly nÆ°á»›c ngon khÃ´ng cáº§n quÃ¡ nhiá»u Ä‘Æ°á»ng hay hÆ°Æ¡ng liá»‡u. OLALA Æ°u tiÃªn trÃ¡i cÃ¢y tÆ°Æ¡i, trÃ  nguyÃªn lÃ¡ vÃ  cÃ  phÃª rang má»›i.</p><div className="stats"><b>100%<small>trÃ¡i cÃ¢y tháº­t</small></b><b>0<small>cháº¥t báº£o quáº£n</small></b><b>30â€²<small>giao táº­n tay</small></b></div></div></div></section>
  <section className="reviews shell"><div className="reviewTitle"><span className="eyebrow">KHÃCH HÃ€NG NÃ“I GÃŒ?</span><h2>Nhá»¯ng ngá»¥m vui<br/>Ä‘Æ°á»£c chia sáº».</h2></div><div className="reviewTrack"><article><div>â˜…â˜…â˜…â˜…â˜…</div><p>â€œTrÃ  thÆ¡m, khÃ´ng quÃ¡ ngá»t. Giao tá»›i nÆ¡i Ä‘Ã¡ váº«n chÆ°a tan nhiá»u.â€</p><b>Minh Anh</b><small>ÄÃ£ Ä‘áº·t 12 láº§n</small></article><article><div>â˜…â˜…â˜…â˜…â˜…</div><p>â€œCÃ  phÃª kem muá»‘i Ä‘áº­m vá»«a Ä‘á»§, pháº§n kem ráº¥t má»‹n vÃ  khÃ´ng bá»‹ ngáº¥y.â€</p><b>HoÃ ng Nam</b><small>KhÃ¡ch hÃ ng thÃ¢n thiáº¿t</small></article><article><div>â˜…â˜…â˜…â˜…â˜…</div><p>â€œNÆ°á»›c Ã©p xanh dá»… uá»‘ng hÆ¡n mÃ¬nh nghÄ©, vá»‹ tÆ°Æ¡i vÃ  khÃ´ng bá»‹ quÃ¡ ná»“ng cáº§n tÃ¢y.â€</p><b>Thu HÃ </b><small>ÄÃ£ Ä‘áº·t 8 láº§n</small></article></div></section>
  <footer id="contact"><div className="shell footer"><div className="brand"><span>o</span>lala</div><p>Äá»“ uá»‘ng tÆ°Æ¡i cho ngÃ y vui hÆ¡n.<br/>Hotline: 090 123 4567</p><div>Instagramã€€Facebookã€€TikTok</div></div></footer>
  {count>0&&!open&&<div className="floatingWrap"><div className="freeProgress"><span style={{width:`${progress}%`}}/>{freeLeft?<small>Mua thÃªm {money(freeLeft)} Ä‘á»ƒ miá»…n phÃ­ giao hÃ ng</small>:<small>ðŸŽ‰ Báº¡n Ä‘Æ°á»£c miá»…n phÃ­ giao hÃ ng</small>}</div><button className="floatingCart" onClick={()=>setOpen(true)} aria-label={`Má»Ÿ giá» hÃ ng cÃ³ ${count} sáº£n pháº©m`}><span className="floatingCount">{count}</span><span><b>Xem giá» hÃ ng</b><small>{count} mÃ³n Ä‘Ã£ chá»n</small></span><strong>{money(subtotal+shipping)}ã€€â†’</strong></button></div>}
  {fly&&<div className="flyToCart">{products.find(p=>p.id===fly)?.icon}</div>}
  {toast&&<div className="toast"><b>âœ“</b><span>{toast}<small>ÄÃ£ cáº­p nháº­t giá» hÃ ng</small></span><button onClick={()=>setToast("")}>Ã—</button></div>}
  {open&&<div className="overlay" onMouseDown={()=>setOpen(false)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}>Ã—</button>
   {!checkout&&!success&&<><h2>Giá» hÃ ng cá»§a báº¡n</h2>{count===0?<div className="empty">ðŸ§ƒ<p>Giá» hÃ ng Ä‘ang trá»‘ng</p><button onClick={()=>setOpen(false)}>Chá»n Ä‘á»“ uá»‘ng</button></div>:<><div className="drawerProgress"><div><span style={{width:`${progress}%`}}/></div><p>{freeLeft?<>ThÃªm <b>{money(freeLeft)}</b> Ä‘á»ƒ Ä‘Æ°á»£c miá»…n phÃ­ giao hÃ ng</>:<>ðŸŽ‰ ÄÆ¡n hÃ ng Ä‘Æ°á»£c miá»…n phÃ­ giao hÃ ng</>}</p></div><div>{products.filter(p=>cart[p.id]).map(p=><div className="cartItem" key={p.id}><span>{p.icon}</span><div><b>{p.name}</b><small>{prefs[p.id]?`${prefs[p.id].size} Â· ${prefs[p.id].sugar} Ä‘Æ°á»ng Â· Ä‘Ã¡ ${prefs[p.id].ice}`:"Size M Â· 50% Ä‘Æ°á»ng Â· Ä‘Ã¡ vá»«a"}</small>{prefs[p.id]?.toppings.length>0&&<small>+ {prefs[p.id].toppings.join(", ")}</small>}<small>{money(itemPrice(p.id,p.price))}</small></div><div className="qty"><button onClick={()=>change(p.id,-1)}>âˆ’</button>{cart[p.id]}<button onClick={()=>add(p.id)}>+</button></div></div>)}</div><div className="summary"><p>Táº¡m tÃ­nh <b>{money(subtotal)}</b></p><p>PhÃ­ giao hÃ ng <b>{shipping?money(shipping):"Miá»…n phÃ­"}</b></p><p className="total">Tá»•ng cá»™ng <b>{money(subtotal+shipping)}</b></p></div><button className="checkout" onClick={()=>setCheckout(true)}>Tiáº¿n hÃ nh Ä‘áº·t hÃ ng</button></>}</>}
   {checkout&&!success&&<form onSubmit={e=>{e.preventDefault();setSuccess(true)}}><button type="button" className="back" onClick={()=>setCheckout(false)}>â† Quay láº¡i giá» hÃ ng</button><h2>ThÃ´ng tin giao hÃ ng</h2><label>Há» vÃ  tÃªn<input required placeholder="Nguyá»…n VÄƒn An"/></label><label>Sá»‘ Ä‘iá»‡n thoáº¡i<input required type="tel" placeholder="09xx xxx xxx"/></label><label>Äá»‹a chá»‰ giao hÃ ng<textarea required placeholder="Sá»‘ nhÃ , Ä‘Æ°á»ng, phÆ°á»ng/xÃ£, quáº­n/huyá»‡n"/></label><label>Ghi chÃº<textarea placeholder="Ãt Ä‘Ã¡, giao táº¡i lá»… tÃ¢n..."/></label><h3>Thanh toÃ¡n</h3><label className={`payment ${pay==="cod"?"selected":""}`}><input type="radio" name="pay" checked={pay==="cod"} onChange={()=>setPay("cod")}/>ðŸ’µ Thanh toÃ¡n khi nháº­n hÃ ng</label><label className={`payment ${pay==="online"?"selected":""}`}><input type="radio" name="pay" checked={pay==="online"} onChange={()=>setPay("online")}/>ðŸ’³ Thanh toÃ¡n trá»±c tuyáº¿n</label>{pay==="online"&&<div className="note">Cá»•ng thanh toÃ¡n sáº½ má»Ÿ sau khi xÃ¡c nháº­n Ä‘Æ¡n.</div>}<button className="checkout" type="submit">Äáº·t hÃ ng Â· {money(subtotal+shipping)}</button></form>}
   {success&&<div className="success"><div>âœ“</div><h2>Äáº·t hÃ ng thÃ nh cÃ´ng!</h2><p>OLALA Ä‘Ã£ nháº­n Ä‘Æ¡n vÃ  sáº½ liÃªn há»‡ xÃ¡c nháº­n trong Ã­t phÃºt.</p><button onClick={()=>{setCart({});setSuccess(false);setCheckout(false);setOpen(false)}}>Tiáº¿p tá»¥c mua hÃ ng</button></div>}
  </aside></div>}
  {selectedProduct&&<div className="overlay detailOverlay" onMouseDown={()=>setSelected(null)}><section className="detailModal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>Ã—</button><div className={`detailPhoto ${selectedProduct.tone}`}><img className={`duo ${selectedProduct.side}`} src={selectedProduct.image} alt={selectedProduct.name}/><div className="liveChoice">Size {size}<br/>{sugar} Ä‘Æ°á»ng Â· Ä‘Ã¡ {ice.toLowerCase()}</div></div><div className="detailBody"><span className="eyebrow">TÃ™Y CHá»ˆNH MÃ“N</span><h2>{selectedProduct.name}</h2><p>{selectedProduct.desc}</p><Option title="Chá»n size" values={["M","L +8.000Ä‘"]} current={size==="L"?"L +8.000Ä‘":"M"} onPick={v=>setSize(v.startsWith("L")?"L":"M")}/><Option title="LÆ°á»£ng Ä‘Æ°á»ng" values={["0%","30%","50%","100%"]} current={sugar} onPick={setSugar}/><Option title="LÆ°á»£ng Ä‘Ã¡" values={["Ãt","Vá»«a","Nhiá»u"]} current={ice} onPick={setIce}/><div className="optionGroup"><b>ThÃªm topping</b><div>{Object.entries(toppingPrices).map(([name,price])=><button key={name} className={toppings.includes(name)?"selected":""} onClick={()=>toggleTopping(name)}>{toppings.includes(name)?"âœ“ ":""}{name} +{money(price)}</button>)}</div></div><button className="checkout addCustomized" onClick={saveChoice}>ThÃªm vÃ o giá» Â· {money(selectedProduct.price+(size==="L"?8000:0)+toppings.reduce((sum,t)=>sum+toppingPrices[t],0))}</button></div></section></div>}
 </main>
}

function Option({title,values,current,onPick}:{title:string,values:string[],current:string,onPick:(value:string)=>void}){return <div className="optionGroup"><b>{title}</b><div>{values.map(v=><button key={v} className={current===v?"selected":""} onClick={()=>onPick(v)}>{v}</button>)}</div></div>}

